openapi: 3.0.3
info:
  title: EazyShop Products APIs Definition
  description: |
    Using this OpenAPI specification, 
    any consumer can understand the API that are exposed by EazyShop. 
  termsOfService: http://eazyshop.com/terms
  contact: 
    name: API Support
    url: https://www.eazyshops.com/support
    email: support@eazyshop.com
  license:
    name: EazyShop License
    url: https://www.eazyshop.com/license/LICENSE-2.0
  version: 0.0.1
servers:
- url: https://development.eazyshop.server.com/v1
  description: Development server
paths:
  /details:
    get:
      summary: List details of the item
      description: Returns the details of the item supported by EazyShop
      responses:
        '200':
          description: Details of the product
          content: 
            application/json:
              schema:
                type: array
                items: 
                  type: object
                  properties: 
                    categoryId:
                      type: integer
                    name:
                      type: string
  /categories/{categoryId}:
    get:
      summary: List all categories
      description: Returns the list of categories supported by EazyShop
      parameters: 
        - name: categoryId
          in: path
          required: true
          schema: 
            type: integer
            minimum: 100
            maximum: 1000
          example: 102
      responses:
        '200':
          description: A list of categories
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  categoryId:
                    type: integer
                  name:
                    type: string
  /products:
    get: 
      summary: List all the products
      description: | 
        Returns the list of propducts supported 
          by EazyShop
      parameters: 
        - name: productId
          in: query
          schema: 
            type: integer
            minimum: 100
            maximum: 1000
          example: 101
      responses: 
        '200':
          description: A list of products
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties: 
                    productId:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
                    categoryName:
                      type: string
                    quantity:
                      type: integer
          
  /products/{productId}:
    get: 
      summary: return product details
      description: | 
        Returns the product details 
          from EazyShop
      parameters: 
        - name: productId
          in: path
          required: true
          schema: 
            type: integer
            minimum: 100
            maximum: 1000
          example: 101
      responses: 
        '200':
          description: Return product details
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  productId:
                    type: integer
                  name:
                    type: string
                  price:
                    type: number
                  categoryName:
                    type: string
                  quantity:
                    type: integer
  /orders:
    post: 
      summary: Create order
      description: |
        Popst order details to EazyShop for processing 
        and shipping
      requestBody: 
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                products: 
                  type: array
                  items: 
                    type: object
                    properties: 
                      productId:
                        type: integer
                      name:
                        type: string
                      price: 
                        type: number
                      categoryName:
                        type: string
                      quantity:
                        type: integer
                address:
                  type: object
                  properties: 
                    addressLine:
                      type: string
                    city:
                      type: string
                    state:
                      type: string
                    zipCode:
                      type: string
      responses: 
        '201':
          description: Order created successfully!
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  orderId:
                    type: integer
    put: 
      summary: Update order
      description: |
        Update order details to EazyShop for processing 
        and shipping
      requestBody: 
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                orderId:
                  type: integer
                products: 
                  type: array
                  items: 
                    type: object
                    properties: 
                      productId:
                        type: integer
                      name:
                        type: string
                      price: 
                        type: number
                      categoryName:
                        type: string
                      quantity:
                        type: integer
                address:
                  type: object
                  properties: 
                    addressLine:
                      type: string
                    city:
                      type: string
                    state:
                      type: string
                    zipCode:
                      type: string
      responses: 
        '200':
          description: Order details updated successfully!
    delete: 
      summary: Delete order
      description: Delete order details from EazyShop
      parameters: 
        - name: orderId
          in: query
          required: true
          schema: 
            type: integer
      responses: 
        '204':
          description: Order has been canceled successfully!
                  


