openapi: 3.0.3
info:
  title: EazyShop Products APIs Definition
  description: |
    Using this OpenAPI specification, 
    any consumer can understand the API that are exposed by EazyShop. 
  termsOfService: http://eazyshop.com/terms
  contact: 
    name: API Support
    url: https://www.eazyshops.com/support
    email: support@eazyshop.com
  license:
    name: EazyShop License
    url: https://www.eazyshop.com/license/LICENSE-2.0
  version: 0.0.1
servers:
- url: https://development.eazyshop.server.com/v1
  description: Development server
paths:
  /categories:
    get:
      summary: List all categories
      description: Returns the list of categories supported by EazyShop
      responses:
        '200':
          description: A list of categories
          content: 
            application/json:
              schema:
                type: array
                items: 
                  type: object
                  properties: 
                    categoryId:
                      type: integer
                    name:
                      type: string
                    